apiVersion: v1 # String - core/v1 - shorthand to v1
kind: Pod # String
metadata: # Dictionary
  name: myapp-pod
  labels: # Dictionary
    app: myapp  # Key value paids
  namespace: default # if default is used, no need to specify namespace
spec:
  containers: # List
    - name: myapp
      image: stacksimplify/kubenginx:1.0.0
      ports: 
        - containerPort: 80


    
